### ISSUE TITLE
Error: Attempt to postMessage on disconnected port

### ISSUE THREAD

**Issue by andrewpwade** [browserpass/browserpass-native#55] opened 2019-04-15 08:17 UTC
### General information

-   Operating system + version: Fedora 29
-   Browser + version: 66.0.2 (64-bit) (from package manager)
-   Information about the host app:
    -   How did you install it?: downloaded a pre-built binary
    -   If installed an official release, put a version (`$ browserpass --version`): 3.0.6
    -   If built from sources, put a commit id (`$ git describe --always`):
-   Information about the browser extension:
    -   How did you install it?: `make BIN=browserpass-linux64 configure && sudo make BIN=browserpass-linux64 install && cd /usr/lib/browserpass/ && sudo make hosts-firefox`
    -   Browserpass extension version as reported by your browser: 3.0.10
### Exact steps to reproduce the problem

1. Restart firefox
1. Click the extension icon

### What should happen?

See a list of passwords

### What happened instead?

Got the error

---

Is the binary meant to be running? I see no browserpass in the process list

```
$ cat /usr/lib/browserpass/hosts/firefox/com.github.browserpass.native.json
{
    "name": "com.github.browserpass.native",
    "description": "Browserpass native component for the Firefox extension",
    "path": "/usr/bin/browserpass-linux64",
    "type": "stdio",
    "allowed_extensions": ["browserpass@maximbaz.com"]
}

$ stat /usr/bin/browserpass-linux64
  File: /usr/bin/browserpass-linux64
  Size: 4305673   	Blocks: 8416       IO Block: 4096   regular file
Device: fd01h/64769d	Inode: 1572939     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Context: system_u:object_r:bin_t:s0
Access: 2019-04-15 08:59:40.529930053 +0100
Modify: 2019-04-15 08:58:12.118382801 +0100
Change: 2019-04-15 08:58:12.123382832 +0100
 Birth: -

```

**Comment by erayd** [comment] 2019-04-15 09:30
> Is the binary meant to be running? I see no browserpass in the process list.

No. The binary is called on demand; it's not a persistent process.

Does `/usr/lib/mozilla/native-messaging-hosts/com.github.browserpass.native.json` exist? It should be a symlink. Where does it point? Does the symlink target exist?

**Comment by andrewpwade** [comment] 2019-04-15 10:57
Hey, thanks for the reply. Yes it's a symlink and the target exists

$ ls -l /usr/lib/mozilla/native-messaging-hosts/com.github.browserpass.native.json
lrwxrwxrwx. 1 root root 69 Apr 15 08:58 /usr/lib/mozilla/native-messaging-hosts/com.github.browserpass.native.json -> /usr/lib/browserpass/hosts/firefox/com.github.browserpass.native.json

**Comment by erayd** [comment] 2019-04-15 10:58
Could you please post the full contents of that file?

**Comment by andrewpwade** [comment] 2019-04-15 11:00
I did, in the initial report :-)

**Comment by maximbaz** [comment] 2019-04-15 11:01
Let's check if your binary is working at all, grab this file: [request-configure.hex.txt](https://github.com/browserpass/browserpass-native/files/3079779/request-configure.hex.txt)

And run:

```
/usr/bin/browserpass-linux64 < /path/to/request-configure.hex.txt
```

What do you see?

**Comment by andrewpwade** [comment] 2019-04-15 11:03
```
$ /usr/bin/browserpass-linux64 < ~/Downloads/request-configure.hex.txt 
�{"status":"ok","version":3000006,"data":{"defaultStore":{"path":"/home/andrew/.password-store","settings":"{}"},"storeSettings":{}}}
```

**Comment by erayd** [comment] 2019-04-15 11:05
> I did, in the initial report :-)

My mistake sorry, I missed that!

A thought - if you run `sudo setenforce 0`, then attempt to use browserpass, does it work? Run `sudo setenforce 1` afterwards to put this setting back.

**Comment by maximbaz** [comment] 2019-04-15 11:08
Would you be able to try in Chromium? Just trying to narrow down where the problem might be located.

**Comment by andrewpwade** [comment] 2019-04-15 11:13
setenforce 0 didn't resolve the issue in FF. It works in Google Chrome though (with setenforce 1).

Thanks for your help so far!

There are some addon debug logs from FF, in case they're helpful (I'm not sure if they're all related to your addon, sorry, but they appeared when I clicked the icon)

> Error: "Attempt to postMessage on disconnected port"
>    promisify moz-extension://5da015e7-aa5c-4ab7-990f-bb616f21a608/js/background.dist.js:3006
> background.dist.js:879:9
> Error: "Error: Attempt to postMessage on disconnected port"
>    run moz-extension://5da015e7-aa5c-4ab7-990f-bb616f21a608/js/popup.dist.js:11967
> popup.dist.js:11918:9
> unreachable code after return statement[Learn More] injected.js:7:2
> [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.removeSheetUsingURIString]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  > location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 65"  data: no]
> TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.[Learn More]

**Comment by erayd** [comment] 2019-04-15 11:21
This is extremely puzzling. Everything about your system config seems to indicate that it ought to be working, and yet it is not.

Stand by, and I will build a Fedora 29 VM to see if I can reproduce it.

**Comment by maximbaz** [comment] 2019-04-15 11:21
Can you go to `about:debugging#addons`, click Debug, and watch Console tab in there, while attempting to use Browserpass - will it contain any error there?

**Comment by samuelmesq** [comment] 2019-04-15 14:34
Same problem for me, everything looks fine with the config files

Operating system + version: Void Linux
Browser + version: firefox-65.0_1
- Information about the host app:
    - How did you install it?: `downloaded a pre-built binary`
    - If installed an official release, put a version ($ browserpass --version): `Browserpass host app version: 3.0.2`

- Information about the browser extension: 
  - Browserpass extension version as reported by your browser: `3.0.10`

Here is a print from about:debugging#addons after i clicked the browserpass icon:
![2019-04-15-142426_1090x641_scrot](https://user-images.githubusercontent.com/716032/56140867-3ffaba80-5f8b-11e9-8e4f-ae37d341d987.png)

**Comment by jbal91** [comment] 2019-04-16 04:27
Also affected. Arch Linux, `browserpass` from repos (3.0.6), Firefox extension version 3.0.12

**Comment by erayd** [comment] 2019-04-16 04:36
@maximbaz Can you reproduce on your Arch box?

**Comment by naggie** [comment] 2019-04-16 06:09
I have the same issue -- native exe on MacOS Mojave, Browserpass-native 3.0.6, Browserpass-extension 3.0.10, Firefox 66.0.3.

Note that I originally had the same issue when the browser extension was updated before I updated the native host exes. I used the zipped EXEs from the releases on github.

**Comment by maximbaz** [comment] 2019-04-16 14:42
It is completely puzzling issue, no I don't reproduce on my Arch, neither with Firefox extension from Web store, nor with `community/browserpass-firefox`. 

To clarify, on both screenshots the only real log message that belongs to Browserpass is "attempt to postMessage on a disconnected port", you can tell this by extension ID (which is different for each of us):

![image](https://user-images.githubusercontent.com/1177900/56217975-6f312a80-6064-11e9-89d2-ca5a3de0964c.png)

Can you guys think of anything unusual in a way your `gpg` is configured? Do you guys use `gpg-agent` with a GUI pinentry program?

Finally can you also try `hosts-firefox-user` goal instead of `hosts-firefox`?

**Comment by samuelmesq** [comment] 2019-04-16 17:06
updated browserpass-native to version `3.0.6`, and firefox extension to `3.0.12` and now it's working for me.

**Comment by naggie** [comment] 2019-04-16 18:00
> Do you guys use gpg-agent with a GUI pinentry program?

Yes, which has worked fine before.

I'll update to the extension version `3.0.12` when the update is pushed, maybe that will fix it for me too.

Here's my `com.github.browserpass.native.json` -- is the filename important by the way?

Location: `.mozilla/native-messaging-hosts`
```
{
    "name": "com.github.browserpass.native",
    "description": "Browserpass native component for the Firefox extension",
    "path": "/usr/local/bin/browserpass",
    "type": "stdio",
    "allowed_extensions": ["browserpass@maximbaz.com"]
}
```

I've installed the prebuilt binary. I assume its location doesn't matter -- mine is in `/usr/local/bin`

**Comment by maximbaz** [comment] 2019-04-16 18:29
> Yes, which has worked fine before.

Just to make it clear, I wasn't asking to make fun of your setup or anything, I simply need to understand why I cannot reproduce the issue and what is common between all of you 🙂

> Here's my com.github.browserpass.native.json -- is the filename important by the way?

Yep, very important, we whitelist it in the browser extension, also see here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#Manifest_location

So I think we solved your mystery, at least, please confirm that when using the proper name everything works :)

**Comment by naggie** [comment] 2019-04-16 18:34
> Just to make it clear, I wasn't asking to make fun of your setup or anything, I simply need to understand why I cannot reproduce the issue and what is common between all of you

I know :)

Assuming the proper name is `com.github.browserpass.native.json`, it does not work still (as that was one of the things I tried as above)

I'll rename it correctly in the dotfiles.

**Comment by maximbaz** [comment] 2019-04-16 18:37
Hey, another idea, if you just launch "browserpass" in terminal, do you get any warnings, or it just hangs with no output?

**Comment by andrewpwade** [comment] 2019-04-16 19:00
I didn't have a pinentry config in my gpg-agent.conf. I have added one now, but that doesn't fix it

Running `/usr/bin/browserpass-linux64` in a terminal hangs with no output. strace shows the last output as:

`read(0, `

**Comment by andrewpwade** [comment] 2019-04-16 19:03
Oh, bingo, `make hosts-firefox-user` works!

**Comment by maximbaz** [comment] 2019-04-16 19:06
Great! But why... Are you the first-time user, or you used browserpass v2? In the latter case, do you know/remember in which location you had `com.dannyvankooten.browserpass.json`?

**Comment by andrewpwade** [comment] 2019-04-16 19:06
Also, I noticed my firefox is `/usr/lib64/firefox/firefox` (lib64) whereas the makefile `hosts-firefox` target seems to be using `/usr/lib/mozilla/native-messaging-hosts...` ? Is that the issue?

**Comment by andrewpwade** [comment] 2019-04-16 19:06
> Great! But why... Are you the first-time user, or you used browserpass v2? In the latter case, do you know/remember in which location you had `com.dannyvankooten.browserpass.json`?

I was using v2 yes. No idea about that file, sorry.

**Comment by jbal91** [comment] 2019-04-16 19:08
I get no output from `browserpass` in terminal, but running `browserpass < request-configure.hex.txt` works:
 
    {"status":"ok","version":3000006,"data":{"defaultStore":{"path":"/home/jbal/.password-store","settings":"{}"},"storeSettings":{}}}

I think I'm just going to switch to passff, at least until the builds in the Arch repos are fixed.

**Comment by andrewpwade** [comment] 2019-04-16 19:09
> `com.dannyvankooten.browserpass.json`

Oh here it is

`/home/andrew/.mozilla/native-messaging-hosts/com.dannyvankooten.browserpass.json`

**Comment by maximbaz** [comment] 2019-04-16 19:11
> Also, I noticed my firefox is /usr/lib64/firefox/firefox (lib64) whereas the makefile hosts-firefox target seems to be using /usr/lib/mozilla/native-messaging-hosts... ? Is that the issue?

Yes, that is most probably the reason! Can you verify, just to be certain? `rm ~/.mozilla/native-messaging-hosts/com.github.browserpass.native.json`, confirm that the extension doesn't work again, then run the command below and confirm that it works again?

```
ln -sfv "/usr/lib/browserpass/hosts/firefox/com.github.browserpass.native.json" "/usr/lib64/mozilla/native-messaging-hosts/com.github.browserpass.native.json"
```

Is browserpass the only app that is installed in `/usr/lib`, and everything else is installed in `/usr/lib64`? I'll read up more on this topic, but at least on my Arch `/usr/lib64` is just a symlink to `/usr/lib`.

**Comment by andrewpwade** [comment] 2019-04-16 19:14
> Yes, that is most probably the reason! Can you verify, just to be certain? `rm ~/.mozilla/native-messaging-hosts/com.github.browserpass.native.json`, confirm that the extension doesn't work again, then run the command below and confirm that it works again?

I had to `/usr/lib64/mozilla/native-messaging-hosts` but yes following your instructions broke then fixed.

> Is browserpass the only app that is installed in /usr/lib, and everything else is installed in /usr/lib64? I'll read up more on this topic, but at least on my Arch /usr/lib64 is just a symlink to /usr/lib.

They're distinct on my system, and...:

```
$ find /usr/lib/ -type f -executable -print | wc -l
1691
$ find /usr/lib64/ -type f -executable -print | wc -l
6914
```

**Comment by maximbaz** [comment] 2019-04-16 19:31
It seems there's no simple way to figure out which lib folder to use, it varies from distro to distro. I guess I'll just document that `-user` configs are preferable, and if you want a system config, you might need to check the location of Firefox and then use something like `make LIB_DIR=/usr/lib64 hosts-firefox`.

**Comment by maximbaz** [comment] 2019-04-16 19:32
@jbal91 are you interested in debugging this issue? You are currently the only known Arch user who has this issue 😉 Are you running a multilib setup? Is `/usr/lib64` also a symlink to `/usr/lib` on your machine?

**Comment by maximbaz** [comment] 2019-04-16 19:37
@naggie let's try a clean setup, please run

```
$ sudo updatedb
$ locate com.github.browserpass.native.json
```

Remove all results except from `/usr/lib/browserpass/` folder (and make a note of what you removed, in case this exercise helps).

Then create a file `~/.mozilla/native-messaging-hosts/com.github.browserpass.native.json` with the contents

```
{
    "name": "com.github.browserpass.native",
    "description": "Browserpass native component for the Firefox extension",
    "path": "/usr/local/bin/browserpass",
    "type": "stdio",
    "allowed_extensions": ["browserpass@maximbaz.com"]
}
```

And please, triple check that the `"path"` points to the correct binary of 3.0.6 version.

**Comment by jbal91** [comment] 2019-04-16 20:58
I got it to work.

I had installed the browser extension for 2.0 from AUR (`firefox-browserpass`), but manually installed 3.0 from AMO. I removed that package, installed `browserpass-firefox` from community, created a new Firefox profile, and it started working. I guess it was loading the old version and the new version at the same time?

**Comment by maximbaz** [comment] 2019-04-16 21:29
Nice job figuring it out 👍 I removed the obsolete `firefox-browserpass` from AUR yesterday, so hopefully we won't hear similar cases anymore.

It's interesting that everyone had a different reason for having issues with Firefox 🙂 

@naggie you are the last person whose mystery we need to solve before closing this issue 😉 (apart from me needing to update README to recommend `-user` versions).

**Comment by maximbaz** [comment] 2019-04-17 08:34
Awesome 👍 

I guess Manjaro users could also just install like this until their repo is synchronized:

```
sudo pacman -U https://www.archlinux.org/packages/community/x86_64/browserpass/download/
sudo pacman -U https://www.archlinux.org/packages/community/any/browserpass-firefox/download/
```

(the links are taken from "Download from mirrow" button [here](https://www.archlinux.org/packages/community/x86_64/browserpass/) and [here](https://www.archlinux.org/packages/community/any/browserpass-firefox/))

**Comment by benjumanji** [comment] 2019-04-17 12:06
I'm on arch, I've never installed manually, I've the 3x series, passing the request hex text test works fine, I've no home folder overrides. I just have the browserpass aur package installed, and the firefox extension installed via firefox. I have no idea how to debug this because there doesn't seem to be anything interesting for me to read log wise.

**Comment by erayd** [comment] 2019-04-17 15:28
@maximbaz Can we have the host package also install browser config to every location it knows about? Seems to me that would have prevented many of the issues that have been reported with v3.

**Comment by maximbaz** [comment] 2019-04-17 17:12
It actually used to be the case on Arch, but I've received some negative feedback about it, people were concerned that `browserpass` was polluting file system with configs for various browsers, when those browsers are not even installed.

I think the approach I have right now for Arch is the best, the system is not polluted when you install `browserpass`, but after installation there's a notice printed about the existence of optional packages `browserpass-firefox` and `browserpass-chromium`, and when users install those dedicated packages, not only host config is properly setup, but also the extension itself gets installed.

I guess the most beneficial action would be for users to lobby packagers of their distros to create packages like `browserpass-chromium` and `browserpass-firefox` in addition to `browserpass`, so that users don't need to do anything besides installing one of the available distro packages.

**Comment by erayd** [comment] 2019-04-17 20:48
I do wonder whether it might be more sensible to install all the browser configs *anyway*. One complaint about extra files, which should still be tracked by the package manager, vs lots of users with a broken setup - to be honest, I think improving the user experience takes priority here, and I'm a bit concerned about just how many users have posted here with problems of that nature.

A middle ground could be to put the configs into a browserpass-config package, and also supply a noop browserpass-noconfig, and have it depends on *one* of those (or -firefox, -chromium etc.), preferring the former. That way anyone who doesn't want the config can opt out, and everyone else will automatically get a working setup without having to understand the host config requirements.

**Comment by maximbaz** [comment] 2019-04-17 21:04
It's worth noting that the vast majority of people who had issues are on OS that don't provide `browserpass-firefox` _at all_, and if they did, we wouldn't be discussing this issue 🙂  I don't have control over how other distros choose to provide their `browserpass` package, but our Makefile supports that, all they have to do is to run `make hosts-*` during the packaging stage and it will include all possible json files 🙂 

But I agree with your sentiment and reasoning, therefore my recommendation to package maintainers is: if you can, provide `browserpass-firefox` like Arch does, if for whatever reason it is problematic, do consider including all hosts json files directly in the `browserpass` package.

On Arch, that does provide `browserpass-firefox` package, so far there was only a single person who didn't immediately realize that such package exists, and they realized this anyway before we had a chance to respond in this thread, so I think it's quite discoverable.

**Comment by maximbaz** [comment] 2019-04-17 21:33
In fact, I've just went through every distro package, seems we are already good everywhere we can:

- Arch and Debian: provide dedicated `browserpass-firefox` / `browserpass-webext`
- NixOS and Gentoo: bundle some hosts json files into `browserpass` directly (I think NixOS bundles all browsers, Gentoo only some)
- macOS homebrew formula has a technical limitation, they are sandboxed and therefore cannot implement this.

So the problem is mostly due to the absence of distro packages for Fedora / Void / Manjaro distros (and others, not mentioned in this thread). 

// If someone is able to create a packages for other distros, please consider doing so, this is very valuable work!

**Comment by mujeebcpy** [comment] 2019-04-19 06:24
i am facing the same problem
Os : Fedora 29
browser : Firefox 66.0.2
i downloaded the precompiled binary. and it works on chrome. getting this error in firefox. i tried firefox-user and created `~/.mozilla/native-messaging-hosts/com.github.browserpass.native.json` this file. but that wont help me. i installed it in /usr/bin

**Comment by maximbaz** [comment] 2019-04-19 09:38
@mujeebcpy please post here `cat ~/.mozilla/native-messaging-hosts/com.github.browserpass.native.json`, and inside there will be `"path"`, do you confirm that that path is valid?

**Comment by mujeebcpy** [comment] 2019-04-19 13:19
```{
    "name": "com.github.browserpass.native",
    "description": "Browserpass native component for the Firefox extension",
    "path": "/usr/bin/browserpasss",
    "type": "stdio",
    "allowed_extensions": ["browserpass@maximbaz.com"]
}

```

i think`/usr/lib/browserpass` is not the installed path

**Comment by maximbaz** [comment] 2019-04-19 13:25
you have browserpass with 3 s in the json file, have you created it manually? why not use Makefile to avoid typos? :)

**Comment by mujeebcpy** [comment] 2019-04-19 13:27
oops. i didnt noticed that. i copied from here. and make install doesn't create this json in .mozilla folder. thats why i created this

**Comment by maximbaz** [comment] 2019-04-19 13:31
Of course [it does](https://github.com/browserpass/browserpass-native/#configure-browsers) 😉 `make hosts-firefox-user` in your case.

But glad you made it work in the end 😉

**Comment by mujeebcpy** [comment] 2019-04-19 13:33
Now ok. I changed `usr/bin/browserpass` to `/usr/bin/browserpass-linux64`. now started working. i also tried make `hosts-firefox-user` by reading comments here. unfortunately that also didn't work.

**Comment by benjumanji** [comment] 2019-04-19 14:20
I think the separate packages are fine and maybe this is off topic so please feel free to tell me to open a new issue but what really threw me was the package descriptions
```
community/browserpass-firefox 3.0.12-1 (392.6 KiB 1.3 MiB) (Installed)
    Firefox extension for Browserpass, browser extension for zx2c4's pass (password manager)
community/browserpass-chromium 3.0.12-1 (528.4 KiB 527.0 KiB) 
    Chromium extension for Browserpass, browser extension for zx2c4's pass (password manager)
community/browserpass 3.0.6-1 (1.0 MiB 4.0 MiB) (Installed)
    Native host app for Browserpass, browser extension for zx2c4's pass (password manager)
```
I actually saw the browserpass-firefox package before reading the readme and dismissed it because I didn't think it was a requirement for the host app to work. I thought it was installing the addon which I thought "I've already installed this via firefox". If I could be so bold I would change the wording to indicate that a) browserpass itself doesn't function without the extra packages and b) change the wording for the browser specific packages to indicate that they contain essential files for the host app to function. When installing a shit load of packages after a hiatus it's easy to miss post install hook messages.

**Comment by maximbaz** [comment] 2019-04-19 15:17
You are absolutely right, `browserpass-firefox` is _not_ a requirement for the host app to work. First and foremost `browserpass-firefox` provides a Firefox extension of a certain version that is guaranteed to be compatible with the `browserpass` native host app; the fact that it is _also_ able to configure itself (which the extension installed from Web Store cannot do) is just a pleasant side-effect.

I have reworded the README a bit to make it more clear:

![image](https://user-images.githubusercontent.com/1177900/56430464-b7e81e00-62c6-11e9-9e69-3e9d2e064401.png)

**Comment by naggie** [comment] 2019-04-22 07:19
> @naggie let's try a clean setup, please run
> 
> ```
> $ sudo updatedb
> $ locate com.github.browserpass.native.json
> ```
> 
> Remove all results except from `/usr/lib/browserpass/` folder (and make a note of what you removed, in case this exercise helps).
> 
> Then create a file `~/.mozilla/native-messaging-hosts/com.github.browserpass.native.json` with the contents
> 
> ```
> {
>     "name": "com.github.browserpass.native",
>     "description": "Browserpass native component for the Firefox extension",
>     "path": "/usr/local/bin/browserpass",
>     "type": "stdio",
>     "allowed_extensions": ["browserpass@maximbaz.com"]
> }
> ```
> 
> And please, triple check that the `"path"` points to the correct binary of 3.0.6 version.

I've tried it -- but unfortunately I still get the same issue. Incidentally I get another problem when running `sudo make hosts-firefox`:

<img width="953" alt="image" src="https://user-images.githubusercontent.com/208440/56488724-24d20280-64d7-11e9-910d-f1591a2b8271.png">

Is there a way I can check the binary itself with something like a `--version` argument? I have checked it's definitely the latest version from the releases page, in addition to compiling it myself as well.

**Comment by maximbaz** [comment] 2019-04-22 08:38
Wait are you on macOS? Why don't you try this [homebrew formula](https://github.com/amar1729/homebrew-formulae)?

Yes you can test the binary by running `/usr/local/bin/browserpass --version`, use full path to where it is installed, and make sure that `~/.mozilla/native-messaging-hosts/com.github.browserpass.native.json` contains exactly the same path to the browserpass binary.

**Comment by naggie** [comment] 2019-04-23 10:20
> Wait are you on macOS? Why don't you try this [homebrew formula](https://github.com/amar1729/homebrew-formulae)?
> 
> Yes you can test the binary by running `/usr/local/bin/browserpass --version`, use full path to where it is installed, and make sure that `~/.mozilla/native-messaging-hosts/com.github.browserpass.native.json` contains exactly the same path to the browserpass binary.

Yes -- I was using the original homebrew formula, which became out of date. I see there's a new tap that's recommended but chose not to use it to mitigate supply chain attacks given that the tap seems unofficial. My dotfiles install script trusts the official binary from here, verifying the sha256sum so if it changes the install will fail.

Running with that flag gives no output.

**Comment by maximbaz** [comment] 2019-04-23 10:22
> Running with that flag gives no output.

This means you don't have the right browserpass binary, here's the expected outcome:

```
❯ browserpass --version        
Browserpass host app version: 3.0.6
```

**Comment by naggie** [comment] 2019-04-23 12:45
Ah -- it seems my install script failed to install the binary. Instead, there was a zero-byte file installed and marked executable which results in a binary that seems to execute, strangely. Undetected because I didn't set `pipefail`.

It still didn't work until I changed the config install directory to `/Library/Application Support/Mozilla/NativeMessagingHosts/`. It now works, thanks and sorry for the additional confusion.

**Comment by maximbaz** [comment] 2019-05-08 09:25
Closing as it seems everyone has got it working 🙂

**Closed by maximbaz** 2019-05-08 09:25 UTC
Labels: support
